# Document:
# http://simiki.org/docs/configuration.html

url: https://jiaqianghuai.github.io/wiki/
title: Qianghuai Jia's Personal Wiki
keywords: wiki
description: personal wiki about my life and work
author: jasonqhjia

root: /wiki/

deploy:
    - type: git
      remote: origin
      branch: gh-pages
      
theme: simple2